# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: "Extract FEMA indicents"

prompts:
  - Extract all declaration requests

providers:
  - id: "file://../../../llm_provider.py"
    label: "openai/gpt-4o-mini"
    config:
      model: "openai/gpt-4o-mini"

tests:
  - vars:
      attachments:
        - path: fema-daily-operation-brief-p9.jpg
      schema:
        syntax: dsl
        multi: true
        content: |
          state_or_tribe_or_territory
          incident_description
          incident_type
          IA bool
          PA bool
          HM bool
          requested str: YYYY-MM-DD, current year is 2025
  - vars:
      attachments:
        - path: fema-daily-operation-brief.pdf
      schema:
        syntax: dsl
        multi: true
        content: |
          state_or_tribe_or_territory
          incident_description
          incident_type
          IA bool
          PA bool
          HM bool
          requested str: YYYY-MM-DD, current year is 2025
