# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: "Extract FEMA indicents"

prompts:
  - Extract all declaration requests

providers:
  - id: "file://../../../llm_provider.py"
    label: "openai/gpt-4o-mini"
    config:
      model: "openai/gpt-4o-mini"
    transform: |
      const parsed = JSON.parse(output)
      return "items" in parsed ? parsed.items : parsed

  - id: "file://../../../llm_provider.py"
    label: "openai/gpt-4o"
    config:
      model: "openai/gpt-4o"
    transform: |
      const parsed = JSON.parse(output)
      return "items" in parsed ? parsed.items : parsed

  - id: "file://../../../llm_provider.py"
    label: "openai/o4-mini-2025-04-16"
    config:
      model: "openai/o4-mini-2025-04-16"
    transform: |
      const parsed = JSON.parse(output)
      return "items" in parsed ? parsed.items : parsed

  - id: "file://../../../llm_provider.py"
    label: "openai/o3"
    config:
      model: "openai/o3"
    transform: |
      const parsed = JSON.parse(output)
      return "items" in parsed ? parsed.items : parsed

  - id: "file://../../../llm_provider.py"
    label: "openai/o1"
    config:
      model: "openai/o1"
    transform: |
      const parsed = JSON.parse(output)
      return "items" in parsed ? parsed.items : parsed

  - id: "file://../../../llm_provider.py"
    label: "anthropic/claude-3-opus-20240229"
    config:
      model: "anthropic/claude-3-opus-20240229"
    transform: |
      const parsed = JSON.parse(output)
      return "items" in parsed ? parsed.items : parsed

  - id: "file://../../../llm_provider.py"
    label: "anthropic/claude-3-5-sonnet-20241022"
    config:
      model: "anthropic/claude-3-5-sonnet-20241022"
    transform: |
      const parsed = JSON.parse(output)
      return "items" in parsed ? parsed.items : parsed

  - id: "file://../../../llm_provider.py"
    label: "anthropic/claude-3-7-sonnet-20250219"
    config:
      model: "anthropic/claude-3-7-sonnet-20250219"
    transform: |
      const parsed = JSON.parse(output)
      return "items" in parsed ? parsed.items : parsed

  - id: "file://../../../llm_provider.py"
    label: "gemini-2.5-pro-preview-03-25"
    config:
      model: "gemini-2.5-pro-preview-03-25"
    transform: |
      const parsed = JSON.parse(output)
      return "items" in parsed ? parsed.items : parsed

  - id: "file://../../../llm_provider.py"
    label: "gemini-1.5-pro-latest"
    config:
      model: "gemini-1.5-pro-latest"
    transform: |
      const parsed = JSON.parse(output)
      return "items" in parsed ? parsed.items : parsed

  - id: "file://../../../llm_provider.py"
    label: "gemini-1.5-flash-latest"
    config:
      model: "gemini-1.5-flash-latest"
    transform: |
      const parsed = JSON.parse(output)
      return "items" in parsed ? parsed.items : parsed

tests:
  - vars:
      attachments:
        - path: fema-daily-operation-brief-p9.jpg
      schema:
        syntax: dsl
        multi: true
        content: |
          state_or_tribe_or_territory
          incident_description
          incident_type
          IA bool
          PA bool
          HM bool
          requested str: YYYY-MM-DD, current year is 2025
    assert:
      # - type: is-json
      #   value: file://expected-schema.json
      - type: equals
        value: file://expected.json

  - vars:
      attachments:
        - path: fema-daily-operation-brief.pdf
      schema:
        syntax: dsl
        multi: true
        content: |
          state_or_tribe_or_territory
          incident_description
          incident_type
          IA bool
          PA bool
          HM bool
          requested str: YYYY-MM-DD, current year is 2025
    assert:
      # - type: is-json
      #   value: file://expected-schema.json
      - type: equals
        value: file://expected.json
  #
