[project]
name = "llm-evals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "llm-gemini>=0.17",
    "llm>=0.24",
    "llm-mlx>=0.3",
    "pydantic-evals>=0.0.55",
    "pandas>=2.2.3",
    "llm-anthropic>=0.15.1",
    "llm-openai-plugin>=0.3",
    "click>=8.1.8",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
extraPaths = ["."]
