[project]
name = "llm-evals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ai-yardstick",
    "llm-gemini>=0.24",
    "llm>=0.24",
    "llm-mlx>=0.3",
    "llm-openai-plugin>=0.3",
    "flask>=3.1.1",
    "llm-ollama>=0.10.0",
    "llm-anthropic==0.16",
    "llm-openrouter>=0.4.1",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
extraPaths = ["."]
