# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: "Grab bag"

prompts:
  - "{{prompt}}"

providers:
  - id: "file://../../../llm_provider.py"
    label: "openai/gpt-4o-mini"
    config:
      model: "openai/gpt-4o-mini"

  - id: "file://../../../llm_provider.py"
    label: "openai/gpt-4o"
    config:
      model: "openai/gpt-4o"

  - id: "file://../../../llm_provider.py"
    label: "gemini-2.5-pro-preview-03-25"
    config:
      model: "gemini-2.5-pro-preview-03-25"

  - id: "file://../../../llm_provider.py"
    label: "qwen3:14b:IQ4_XS"
    config:
      model: "hf.co/unsloth/Qwen3-14B-GGUF:IQ4_XS"

  - id: "file://../../../llm_provider.py"
    label: "gemma3:12b:Q4_0"
    config:
      model: "hf.co/unsloth/gemma-3-12b-it-GGUF:Q4_0"

  - id: "file://../../../llm_provider.py"
    label: "gemma-3-27b-it"
    config:
      model: "gemma-3-27b-it"

  - id: "file://../../../llm_provider.py"
    label: "anthropic/claude-3-opus-20240229"
    config:
      model: "anthropic/claude-3-opus-20240229"

  - id: "file://../../../llm_provider.py"
    label: "anthropic/claude-3-5-sonnet-20241022"
    config:
      model: "anthropic/claude-3-5-sonnet-20241022"

  - id: "file://../../../llm_provider.py"
    label: "anthropic/claude-3-7-sonnet-20250219"
    config:
      model: "anthropic/claude-3-7-sonnet-20250219"

  - id: "file://../../../llm_provider.py"
    label: "anthropic/claude-sonnet-4-0"
    config:
      model: "anthropic/claude-sonnet-4-0"

  - id: "file://../../../llm_provider.py"
    label: "anthropic/claude-opus-4-0"
    config:
      model: "anthropic/claude-opus-4-0"

tests: https://docs.google.com/spreadsheets/d/1mr8K_IP4yJP_cAHGm_OsQXwJg_7WpqchgMbvMpAuCdM/edit?gid=0
