# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: "Trump storylines"
evaluateOptions:
  maxConcurrency: 1

prompts:
  - |-
    Is this article primarily about a new action or announcement by the Trump administration/White House/Executive? Respond simply with "yes" or "no" .
    {{headline}}
    {{content}}
  - |-
    Does this describe a specific, new, official action or formal announcement already taken/made by the Trump administration? Answer only "yes" or "no".
    {{headline}}
    {{content}}

providers:
  - id: "file://llm_provider.py"
    label: "llama-3.2-3b-4bit"
    # llm mlx download-model mlx-community/Llama-3.2-3B-Instruct-4bit -a llama-3.2-3b-4bit
    config:
      model: "llama-3.2-3b-4bit"
      pythonExecutable: ".venv/bin/python"

tests: "file://tests.jsonl"
