# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: "Political fundraising emails"

prompts:
  - |
    Given this political fundraising email, respond with the name of the committee in the disclaimer that begins with Paid for by but does not include Paid for by, the committee address or the treasurer name. If no committee is present, return "None". Do not include any other text, no yapping.
    name: {{name}}
    email: {{email}}
    subject: {{subject}}
    body: {{body}}

providers:
  - id: "file://../../../llm_provider.py"
    label: "openai/gpt-4.1-mini-2025-04-14"
    config:
      model: "openai/gpt-4.1-mini-2025-04-14"
      transform_func: to_uppercase

  - id: "file://../../../llm_provider.py"
    label: "openai/gpt-4o-mini"
    config:
      model: "openai/gpt-4o-mini"
      transform_func: to_uppercase

  - id: "file://../../../llm_provider.py"
    label: "openai/o4-mini-2025-04-16"
    config:
      model: "openai/o4-mini-2025-04-16"
      transform_func: to_uppercase

  # - id: "file://../../../llm_provider.py"
  #   label: "anthropic/claude-3-5-haiku-latest"
  #   config:
  #     model: "anthropic/claude-3-5-haiku-latest"
  #     transform_func: to_uppercase

  - id: "file://../../../llm_provider.py"
    label: "gemini-1.5-flash-002"
    config:
      model: "gemini-1.5-flash-002"
      transform_func: to_uppercase

  - id: "file://../../../llm_provider.py"
    label: "gemini-2.0-flash-lite"
    config:
      model: "gemini-2.0-flash-lite"
      transform_func: to_uppercase

  - id: "file://../../../llm_provider.py"
    label: "gemini-2.0-flash"
    config:
      model: "gemini-2.0-flash"
      transform_func: to_uppercase

  - id: "file://../../../llm_provider.py"
    label: "llama-3.2-3b-4bit"
    config:
      model: "llama-3.2-3b-4bit"
      transform_func: to_uppercase

  - id: "file://../../../llm_provider.py"
    label: "gemma3:12b"
    config:
      model: "gemma3:12b"
      transform_func: to_uppercase

tests: file://tests.csv
