# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: "Trump storylines"

prompts:
  - Is this article primarily about a new action or announcement by the Trump administration/White House/Executive? Respond simply with "true" or "false".\n{{headline}}\n{{content}}
  - Is this about Trump? "true" or "false" .\n{{headline}}\n{{content}}

providers:
  - id: "file://../../../llm_provider.py"
    label: "openai/gpt-4o-mini"
    config:
      model: "openai/gpt-4o-mini"
      transform_func: parse_boolean

  - id: "file://../../../llm_provider.py"
    label: "wapo"
    config:
      model: "wapo"
      transform_func: parse_boolean

  - id: "file://../../../llm_provider.py"
    label: "gemma3:12b"
    config:
      model: "gemma3:12b"
      transform_func: parse_boolean

  - id: "file://../../../llm_provider.py"
    label: "gemma-3-27b-it"
    config:
      model: "gemma-3-27b-it"
      transform_func: parse_boolean

tests: file://tests.csv
