[project]
name = "llm-evals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "llm-gemini>=0.17",
    "llm>=0.24",
    "llm-mlx>=0.3",
]
