# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: "Trump storylines - Categories"

prompts:
  - |
    Put this article into one of the following categories. Use the most specific category that makes sense. If you are unsure, respond Other.

    The allowed categories are:
    Abortion, AI, Associated Press, Birthright citizenship, CFPB, Climate, Crypto, D.C., Debt ceiling, DEI in schools, DEI in the federal government, Department of Education, Deportations, DOGE, End birthright citizenship, Eric Adams case, Expanding executive power, Federal funding, Federal grant pause, Federal office space, Federal worker buyout, Federal workers return to office, Federal workforce reductions, FEMA, Firing government watchdogs, Food safety, Foreign aid, Foreign policy, Gaza, Government shutdown, Guantánamo Bay, Health agencies' communications pause, Health care, Immigration policy, Interest rates, Iran, Islamic State, Israel, Jan. 6, Kennedy Center, NIH, NYC congestion toll, Other, Panama Canal, Pardons, Reclassifying federal jobs, Sanctions, Senior government officials ousted, Taiwan, Targeting political enemies, Targeting protesters, Tariffs, The media, TikTok ban, Transgender policy, U.S.-Mexico border, USAID, USPS, War in Ukraine, World Health Organization

    Respond ONLY with the category.

    {{headline}}
    {{content}}

providers:
  - id: "file://../../../../llm_provider.py"
    label: "openai/gpt-4o"
    config:
      model: "openai/gpt-4o"

  - id: "file://../../../../llm_provider.py"
    label: "openai/gpt-4o-mini"
    config:
      model: "openai/gpt-4o-mini"

  - id: "file://../../../../llm_provider.py"
    label: "qwen3:8b:Q4_0"
    config:
      model: "hf.co/unsloth/Qwen3-8B-GGUF:Q4_0"
      transform_func: strip_think_tags

  - id: "file://../../../../llm_provider.py"
    label: "qwen3:14b:IQ4_XS"
    config:
      model: "hf.co/unsloth/Qwen3-14B-GGUF:IQ4_XS"
      transform_func: strip_think_tags

  - id: "file://../../../../llm_provider.py"
    label: "qwen3:30b-a3b:IQ4_XS"
    config:
      model: "hf.co/unsloth/Qwen3-30B-A3B-GGUF:IQ4_XS"
      transform_func: strip_think_tags

  - id: "file://../../../../llm_provider.py"
    label: "gemma3:12b:IQ4_XS"
    config:
      model: "hf.co/unsloth/gemma-3-12b-it-GGUF:IQ4_XS"

  - id: "file://../../../../llm_provider.py"
    label: "gemma3:12b:Q4_0"
    config:
      model: "hf.co/unsloth/gemma-3-12b-it-GGUF:Q4_0"

  - id: "file://../../../../llm_provider.py"
    label: "gemma-3-27b-it"
    config:
      model: "gemma-3-27b-it"

tests: file://tests.csv
